language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - docker
  - postgresql

branches:
  only:
  - develop
  - sandbox
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
      - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: deadlinez
  on:
    repo: Alex-Kuz/TaradosFeroces-02-2018
    branch: docker
  skip_cleanup: true


