sudo: true
dist: trusty

branches:
  only:
  - develop
  - sandbox
  - docker

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t deadlinez -f Dockerfile ./
      - docker images
      - docker tag deadlinez $DOCKER_USERNAME/deadlinez
      - docker push $DOCKER_USERNAME/deadlinez
    - stage: test
      script: docker run --rm -p 8080:8080 $DOCKER_USERNAME/deadlinez


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: deadlinez
  on:
    repo: Alex-Kuz/TaradosFeroces-02-2018
    branch: docker
  skip_cleanup: true
