language: java
sudo: required

jdk:
  - oraclejdk8

branches:
  only:
  - develop
  - sandbox

before_install:
  - echo "start building"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: deadlinez
  on:
    repo: Alex-Kuz/TaradosFeroces-02-2018
    branch: sandbox
  skip_cleanup: true

install:
  - mvn checkstyle:check
  - mvn test
