sudo: required

services:
  - docker

#branches:
#  only:
#  - develop
#  - sandbox
#  - docker

before_install:
      - docker build -t deadlinez ./
      - docker images

install:
      - docker run --rm -p 8080:8080 $DOCKER_USERNAME/deadlinez


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: deadlinez
  on:
    repo: Alex-Kuz/TaradosFeroces-02-2018
    branch: docker
  skip_cleanup: true
