language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - postgresql

before_install:
  - docker build -t deadlinez -f Dockerfile ./

branches:
  only:
  - develop
  - sandbox

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: deadlinez
  on:
    repo: Alex-Kuz/TaradosFeroces-02-2018
    branch: sandbox
  skip_cleanup: true

install:
  - docker run -p 8080:8080 --name deadlinez deadlinez
