sudo: required

language: java
jdk:
  - oraclejdk9

addons:
  postgresql: "9.6"
  apt:
    packages:
      - sshpass

services:
  - postgresql
  - mongodb

before_install:
    - psql -h 127.0.0.1 -c "create user $DEADLINEZ_PG_USER with password '$DEADLINEZ_PG_PASSWORD';" -U postgres
    - psql -h 127.0.0.1 -c "create database $DEADLINEZ_PG_DB;" -U postgres
    - psql -h 127.0.0.1 -c "grant all on database $DEADLINEZ_PG_DB to $DEADLINEZ_PG_USER;" -U postgres
    - sleep 15
    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
    - mvn test -B

after_success:
    - zip -r -9 target.zip target/*
    - sha256sum target.zip
    - sha256sum target/deadlinez-1.0.0.jar
   
