sudo: required

language: java
jdk:
  - oraclejdk9

services:
  - docker

#branches:
#  only:
#  - develop
#  - sandbox
#  - docker

before_install:
    - docker build -t deadlinez ./
    - docker images

script:
    - docker run --rm -p 8080:8080 deadlinez tests


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: deadlinez
  on:
    repo: Alex-Kuz/TaradosFeroces-02-2018
    branch: sandbox
  skip_cleanup: true
