DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
  id       BIGSERIAL PRIMARY KEY,

  login    TEXT NOT NULL UNIQUE,
  email    TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,

  name     TEXT DEFAULT '',
  avatar   TEXT DEFAULT '',

  points   BIGINT DEFAULT 0
);